
/* This file is part of Jeedom.
 *
 * Jeedom is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Jeedom is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Jeedom. If not, see <http://www.gnu.org/licenses/>.
 */
 
 
$('.eqLogicAttr[data-l1key=configuration][data-l2key=widgettelecommande]').on('change', function () {

	var selected_wtvp = $('.eqLogicAttr[data-l1key=configuration][data-l2key=widgettelecommande]').val();
	//$('#div_alert').showAlert({message: selected_wtvp, level: 'success'});
	if (selected_wtvp == 'remote1') {
		$('#alerte_info_tvp').removeClass('alert alert-info');
		$('#alerte_info_tvp').text('');	
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(0)').val(37);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(0)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(0)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(1)').val(27);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(1)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(1)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(2)').val(28);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(2)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(2)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(3)').val(29);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(3)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(3)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(4)').val(30);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(4)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(4)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(5)').val(31);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(5)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(5)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(6)').val(32);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(6)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(6)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(7)').val(33);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(7)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(7)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(8)').val(34);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(8)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(8)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(9)').val(35);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(9)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(9)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(10)').val(13);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(10)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(10)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(11)').val(45);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(11)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(11)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(12)').val(22);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(12)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(12)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(13)').val(10);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(13)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(13)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(14)').val(15);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(14)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(14)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(15)').val(19);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(15)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(15)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(16)').val(17);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(16)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(16)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(17)').val(20);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(17)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(17)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(18)').val(16);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(18)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(18)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(19)').val(18);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(19)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(19)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(20)').val(14);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(20)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(20)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(21)').val(39);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(21)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(21)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(22)').val(54);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(22)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(22)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(23)').val(55);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(23)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(23)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(24)').val(6);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(24)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(24)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(25)').val(11);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(25)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(25)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(26)').val(8);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(26)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(26)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(27)').val(50);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(27)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(27)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(28)').val(51);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(28)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(28)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(29)').val(52);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(29)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(29)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(30)').val(53);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(30)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(30)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(31)').val(12);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(31)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(31)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(32)').val(40);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(32)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(32)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(33)').val(25);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(33)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(33)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(34)').val(41);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(34)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(34)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(35)').val(1);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(35)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(35)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(36)').val(47);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(36)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(36)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(37)').val(23);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(37)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(37)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(38)').val(3);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(38)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(38)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(39)').val(5);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(39)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(39)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(40)').val(42);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(40)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(40)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(41)').val(46);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(41)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(41)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(42)').val(7);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(42)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(42)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(43)').val(4);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(43)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(43)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(44)').val(49);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(44)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(44)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(45)').val(21);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(45)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(45)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(46)').val(2);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(46)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(46)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(47)').val(36);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(47)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(47)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(48)').val(38);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(48)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(48)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(49)').val(48);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(49)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(49)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(50)').val(57);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(50)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(50)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(51)').val(44);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(51)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(51)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(52)').val(24);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(52)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(52)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(53)').val(26);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(53)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(53)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(54)').val(43);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(54)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(54)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(55)').val(56);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(55)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(55)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(56)').val(9);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(56)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(56)').prop('checked', true);
	}	
	if (selected_wtvp == 'remote2') {
		$('#alerte_info_tvp').addClass('alert alert-info');
		$('#alerte_info_tvp').text('{{Attention, les boutons suivants ne sont pas actifs avec ce visuel: Guide, 3D, Smart TV & List}}');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(0)').val(41);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(0)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(0)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(1)').val(31);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(1)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(1)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(2)').val(32);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(2)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(2)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(3)').val(33);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(3)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(3)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(4)').val(34);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(4)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(4)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(5)').val(35);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(5)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(5)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(6)').val(36);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(6)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(6)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(7)').val(37);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(7)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(7)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(8)').val(38);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(8)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(8)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(9)').val(39);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(9)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(9)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(10)').val(11);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(10)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(10)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(11)').val(8);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(11)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(11)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(12)').val(18);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(12)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(12)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(13)').val(30);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(13)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(13)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(14)').val(22);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(14)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(14)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(15)').val(23);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(15)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(15)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(16)').val(16);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(16)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(16)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(17)').val(19);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(17)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(17)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(18)').val(15);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(18)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(18)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(19)').val(17);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(19)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(19)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(20)').val(13);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(20)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(20)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(21)').val(45);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(21)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(21)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(22)').val(54);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(22)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(22)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(23)').val(55);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(23)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(23)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(24)').val(7);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(24)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(24)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(25)').val(46);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(25)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(25)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(26)').val(28);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(26)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(26)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(27)').val(50);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(27)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(27)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(28)').val(51);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(28)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(28)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(29)').val(52);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(29)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(29)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(30)').val(53);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(30)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(30)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(31)').val(12);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(31)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(31)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(32)').val(14);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(32)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(32)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(33)').val(25);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(33)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(33)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(34)').val(43);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(34)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(34)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(35)').val(1);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(35)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(35)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(36)').val(47);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(36)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(36)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(37)').val(20);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(37)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(37)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(38)').val(3);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(38)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(38)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(39)').val(6);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(39)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(39)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(40)').val(21);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(40)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(40)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(41)').val(4);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(41)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(41)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(42)').val(27);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(42)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(42)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(43)').val(5);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(43)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(43)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(44)').val(49);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(44)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(44)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(45)').val(9);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(45)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(45)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(46)').val(2);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(46)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(46)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(47)').val(40);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(47)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(47)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(48)').val(42);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(48)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(48)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(49)').val(48);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(49)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(49)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(50)').val(57);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(50)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(50)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(51)').val(44);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(51)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(51)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(52)').val(24);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(52)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(52)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(53)').val(26);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(53)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(53)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(54)').val(10);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(54)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(54)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(55)').val(56);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(55)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(55)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(56)').val(29);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(56)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(56)').prop('checked', true);		
	}	
	if (selected_wtvp == 'remote3') {
		$('#alerte_info_tvp').removeClass('alert alert-info');
		$('#alerte_info_tvp').text('');	
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(0)').val(41);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(0)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(0)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(1)').val(31);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(1)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(1)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(2)').val(32);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(2)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(2)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(3)').val(33);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(3)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(3)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(4)').val(34);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(4)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(4)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(5)').val(35);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(5)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(5)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(6)').val(36);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(6)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(6)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(7)').val(37);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(7)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(7)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(8)').val(38);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(8)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(8)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(9)').val(39);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(9)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(9)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(10)').val(11);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(10)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(10)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(11)').val(8);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(11)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(11)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(12)').val(18);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(12)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(12)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(13)').val(30);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(13)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(13)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(14)').val(22);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(14)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(14)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(15)').val(23);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(15)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(15)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(16)').val(16);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(16)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(16)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(17)').val(19);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(17)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(17)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(18)').val(15);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(18)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(18)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(19)').val(17);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(19)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(19)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(20)').val(13);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(20)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(20)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(21)').val(45);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(21)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(21)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(22)').val(54);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(22)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(22)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(23)').val(55);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(23)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(23)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(24)').val(7);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(24)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(24)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(25)').val(46);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(25)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(25)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(26)').val(28);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(26)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(26)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(27)').val(50);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(27)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(27)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(28)').val(51);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(28)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(28)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(29)').val(52);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(29)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(29)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(30)').val(53);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(30)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(30)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(31)').val(12);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(31)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(31)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(32)').val(14);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(32)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(32)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(33)').val(25);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(33)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(33)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(34)').val(43);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(34)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(34)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(35)').val(1);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(35)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(35)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(36)').val(47);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(36)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(36)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(37)').val(20);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(37)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(37)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(38)').val(3);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(38)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(38)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(39)').val(6);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(39)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(39)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(40)').val(21);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(40)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(40)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(41)').val(4);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(41)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(41)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(42)').val(27);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(42)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(42)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(43)').val(5);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(43)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(43)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(44)').val(49);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(44)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(44)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(45)').val(9);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(45)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(45)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(46)').val(2);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(46)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(46)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(47)').val(40);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(47)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(47)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(48)').val(42);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(48)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(48)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(49)').val(48);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(49)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(49)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(50)').val(57);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(50)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(50)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(51)').val(44);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(51)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(51)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(52)').val(24);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(52)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(52)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(53)').val(26);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(53)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(53)').prop('checked', true);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(54)').val(10);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(54)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(54)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(55)').val(56);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(55)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(55)').prop('checked', false);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(56)').val(29);
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(56)').attr('readonly','readonly');
		$('.cmdAttr[data-l1key=isVisible]:eq(56)').prop('checked', false);

	}	
	if (selected_wtvp == 'name') {
		$('#alerte_info_tvp').removeClass('alert alert-info');
		$('#alerte_info_tvp').text('');	
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(0)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(1)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(2)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(3)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(4)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(5)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(6)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(7)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(8)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(9)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(10)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(11)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(12)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(13)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(14)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(15)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(16)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(17)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(18)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(19)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(20)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(21)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(22)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(23)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(24)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(25)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(26)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(27)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(28)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(29)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(30)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(31)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(32)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(33)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(34)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(35)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(36)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(37)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(38)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(39)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(40)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(41)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(42)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(43)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(44)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(45)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(46)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(47)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(48)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(49)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(50)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(51)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(52)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(53)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(54)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(55)').removeAttr('readonly');
		$('.cmdAttr[data-l1key=configuration][data-l2key=order]:eq(56)').removeAttr('readonly');
	}
});



function addCmdToTable(_cmd) {

    if (!isset(_cmd)) {
        var _cmd = {configuration: {}};
    }
    if (!isset(_cmd.configuration)) {
        _cmd.configuration = {};
    }
	if (_cmd.configuration.key_data != 'WidgetVolume') {
		var tr = '<tr class="cmd" data-cmd_id="' + init(_cmd.id) + '">';
		tr += '<td class="name" >';
		tr += '<input class="cmdAttr form-control input-sm" data-l1key="id" style="display : none;">';
		tr += '<input class="cmdAttr form-control input-sm" data-l1key="name"></td>';
		tr += '<td ><input class="cmdAttr form-control input-sm" data-l1key="configuration" data-l2key="key_data" readonly="readonly"></td>';
		tr += '<td><span><input type="checkbox" class="cmdAttr" data-l1key="isVisible" checked/> {{Afficher}}</span></td>';
		tr += '<td><span><input class="cmdAttr form-control input-sm " style="width:50px" data-l1key="configuration" data-l2key="order" /></span></td>';    
		tr += '<td>';
		if (is_numeric(_cmd.id)) {
			tr += '<a class="btn btn-default btn-xs cmdAction" data-action="test"><i class="fas fa-rss"></i> {{Tester}}</a>';
		}
		tr += '</td>';
		tr += '</tr>';
		$('#table_cmd tbody').append(tr);
		$('#table_cmd tbody tr:last').setValues(_cmd, '.cmdAttr');
		jeedom.cmd.changeType($('#table_cmd tbody tr:last'), init(_cmd.subType));
	} else 
	{
		var tr = '<tr class="cmd" data-cmd_id="' + init(_cmd.id) + '" style="display : none;">';
		tr += '<td class="name" >';
		tr += '<input class="cmdAttr form-control input-sm" data-l1key="id" style="display : none;">';
		tr += '<input class="cmdAttr form-control input-sm" data-l1key="name"></td>';
		tr += '<td ><input class="cmdAttr form-control input-sm" data-l1key="configuration" data-l2key="key_data" readonly="readonly"></td>';
		tr += '<td><span><input type="checkbox" class="cmdAttr" data-l1key="isVisible" checked/> {{Afficher}}</span></td>';
		tr += '<td><span><input class="cmdAttr form-control input-sm " style="width:50px" data-l1key="configuration" data-l2key="order" /></span></td>';    
		tr += '<td>';
		if (is_numeric(_cmd.id)) {
			tr += '<a class="btn btn-default btn-xs cmdAction" data-action="test"><i class="fas fa-rss"></i> {{Tester}}</a>';
		}
		tr += '</td>';
		tr += '</tr>';
		$('#table_cmd tbody').append(tr);
		$('#table_cmd tbody tr:last').setValues(_cmd, '.cmdAttr');
		jeedom.cmd.changeType($('#table_cmd tbody tr:last'), init(_cmd.subType));
	}
}